### ISSUE TITLE
Any way to add more reaction buttons?

### ISSUE THREAD

**Issue by Chiggy-Playz** [robertwayne/dpymenus#18]
Hello! I am using PaginatedMenu and by default when I start it, there are 3 buttons. Go forward, backward, and cancel. Now I would like to add 2 buttons, and remove the "cancel" button. The Buttons I want to add, are "Go to first page" and "Go to last page". Is it possible?

**Comment by robertwayne** [comment]
Start/end and custom buttons are available in the development branch, but I can't guarantee any stability with that due to several API changes.

I've been busy but I'll see if I can push that out later today.

**Comment by Chiggy-Playz** [comment]
@robertwayne  ok. I will be looking forward to it. This is a really awesome library. Keep the work up. Do you have a discord server ? I would prefer to talk there heh

**Comment by robertwayne** [comment]
No specific server _(library doesn't have enough people using it to really justify it)_, but you can DM me at Rob#0013 on Discord if you wanna chat!

**Comment by robertwayne** [comment]
@Chiggy-Playz I am fairly close to the v1.0.0 release -- but I need to do a lot of testing and update documentation. If you are interested in trying the new features, you can do:

`pip install git+https://github.com/robertwayne/dpymenus@fluent-interface-api --upgrade`

The *examples/paginated_menu_example.py* has been updated, which should include enough information to update your own code. If you have any questions you can DM me on Discord or reply here. I'll hopefully be able to update all the docs and finish testing within the next couple days if you'd prefer to remain on the current version.

In the release version, you can call:
```python
menu = PaginatedMenu(ctx)
menu.show_skip_buttons()  # this will add buttons that go to the first and last page
menu.hide_cancel_button()  # this does what it sounds like
```

**[Docs for the dev branch are available as well.](https://dpymenus.readthedocs.io/en/fluent-interface-api/#paginatedmenu)**

**Comment by Chiggy-Playz** [comment]
@robertwayne Thank you so much for the effort you are making. I sent you a friend request on discord. Also I may have found a bug, and I would like to discuss more of it on discord.
