### ISSUE TITLE
Reactions do not work in private messages.

### ISSUE THREAD

**Issue by shitass420** [robertwayne/dpymenus#27]
I am using the code below for my help menu however, it sends the menu to the users pm's but the reactions are not working.

    help_menu = PaginatedMenu(ctx)
    help_menu.add_pages(pages)
    help_menu.set_timeout(120)
    help_menu.show_page_numbers()
    help_menu.allow_multisession()
    help_menu.set_destination(ctx.author)
    return await help_menu.open()

**Comment by robertwayne** [comment]
Hi, thanks for pointing this bug out -- I haven't done a full battery of tests, but for now you can try the dev branch with:

`pip install git+git://github.com/robertwayne/dpymenus.git@1.2.3 --upgrade`

**Comment by shitass420** [comment]
Thanks. Works perfectly now.
