### ISSUE TITLE
Add `.allow_multisession()` on menus other than Paginated Menus

### ISSUE THREAD

**Issue by RaymondLWong** [robertwayne/dpymenus#36]
Is it possible to have `.allow_multisession()` on other menus as well? I find many users try to open a second `ButtonMenu` without closing or waiting for the previous menu to timeout. I think it's more user friendly if you add and enable `.allow_multisession()` by default.

**Comment by robertwayne** [comment]
Yeah, this has been on my list of things to do for a while. It's just been pretty low priority. 

Changing the default is something I will be doing in v2, but I will look at a small patch tomorrow to at least make this usable from other menus.
