### ISSUE TITLE
Make it possible to call a `refresh()` function?

### ISSUE THREAD

**Issue by RaymondLWong** [robertwayne/dpymenus#39]
For example, if I wanted to edit an older message created with `ButtonMenu()` or `ButtonMenu().open()`. Useful for things like trading, when I want to update 2 messages simultaneously. Or alternatively, expose the Discord Message ID, so I can manually edit it later.

**Comment by robertwayne** [comment]
Hmm, you're referring to the menu message itself?

You can access it with the `output` attribute on your menu object instance. That contains the message object, which has the message ID.

I'll add a helper function to the v2 roadmap though, to make it cleaner.

**Comment by RaymondLWong** [comment]
Yep, that's exactly what I was looking for!
