### ISSUE TITLE
menus dont work without manage message permission

### ISSUE THREAD

**Issue by takipsizad** [robertwayne/dpymenus#40]

**Comment by robertwayne** [comment]
Removing reactions requires this permission, as well as deleting command messages. The latter can be disabled with a menu option, but right now I don't have a built-in way to handle not having the permission at all. This was primarily a design choice, as it makes menus feel smoother -- though there are benefits to disabling it for a degraded experience *(like tighter permissions, less API hits)*.

I will consider it for v2 as a fallback option when missing permissions.
