### ISSUE TITLE
How i can add timeout to ButtonMenu?

### ISSUE THREAD

**Issue by Animatea** [robertwayne/dpymenus#43]
Just i tried
```py
        menu = Paginator(ctx)
        menu.set_timeout(10)
        menu.add_pages([page1, page2, page3, page4])
        await menu.open()
```

and like this

```py
class Paginator(ButtonMenu):

    async def _cleanup_reactions(self):
        await self.output.delete()
```
and just nothing happens, but in the second option, the message is deleted when you click on any reaction and an error pops up that "message was not found"

**Comment by robertwayne** [comment]
I guess my first question is what your goal is with overriding that method?

`_cleanup_reactions` is called on every iteration of the menu loop to remove old reactions when the page changes, so what is happening is that the menu will go on to its next iteration and tries accessing the `output`, which it expects to be there. Timeouts are handled by an internal method in `BaseMenu` called `_execute_timeout`, so you can override that if you're looking to change functionality from the default behavior.

That said, the default timeout behavior should 'just work' on anything that inherits from a *Menu class. Is there something specific you are trying to accomplish which isn't working?

**Comment by Animatea** [comment]
In paginatedmenu timeout works, but in buttonmenu - no

**Comment by robertwayne** [comment]
I'm assuming you are, but can you just confirm your using the latest version 1.3.1?

Previous versions did have a big with button menu timeouts.

**Comment by Animatea** [comment]
ohhh yes thank you so much..
