### ISSUE TITLE
Cannot import it

### ISSUE THREAD

**Issue by EinWortspiel** [robertwayne/dpymenus#48]
I am trying to use this module but all the time it says "ModuleNotFoundError: No module named 'dpymenus'". I installed it with "pip install dpymenus" and I also tried to reinstall it but nothing works.

If this is important I am using python 3.9.0

**Comment by robertwayne** [comment]
Are you running the project with the virtual environment active / installing it to the venv?

Can you do `pip list` and show me what the output is?

**Comment by EinWortspiel** [comment]
> Are you running the project with the virtual environment active / installing it to the venv?
> 
> Can you do `pip list` and show me what the output is?

When I do "pip list" it shows this is my cmd 

aiohttp                   3.7.4.post0
altgraph                  0.17
art                       5.1
async-timeout             3.0.1
attrs                     20.3.0
auto-py-to-exe            2.8.0
bottle                    0.12.19
bottle-websocket          0.2.9
certifi                   2020.12.5
cffi                      1.14.5
chardet                   3.0.4
click                     7.1.2
colorama                  0.4.4
discord.py                1.6.0
dpymenus                  1.3.1
dsdev-utils               1.0.4
Eel                       0.12.4
emoji                     0.6.0
future                    0.18.2
getmac                    0.8.2
gevent                    21.1.2
gevent-websocket          0.10.1
googletrans               3.0.0
greenlet                  1.0.0
gTTS                      2.2.2
h11                       0.9.0
h2                        3.2.0
hpack                     3.0.0
hstspreload               2020.12.22
httpcore                  0.9.1
httpx                     0.13.3
hyperframe                5.2.0
idna                      2.10
imgurpython               1.1.7
Menu                      3.2.2
Menus                     0.2.0
multidict                 5.1.0
pefile                    2019.4.18
Pillow                    8.2.0
praw                      7.2.0
prawcore                  2.0.0
pycparser                 2.20
pyinstaller               4.2
pyinstaller-hooks-contrib 2021.1
pypresence                4.2.0
pywin32-ctypes            0.2.0
requests                  2.25.1
rfc3986                   1.4.0
selenium                  3.141.0
six                       1.15.0
sniffio                   1.2.0
typing-extensions         3.7.4.3
update-checker            0.18.0
urllib3                   1.26.4
websocket-client          0.58.0
whichcraft                0.6.1
yarl                      1.6.3
zope.event                4.5.0
zope.interface            5.3.0
