### ISSUE TITLE
Initial page on PaginatedMenu.open()

### ISSUE THREAD

**Issue by huantianad** [robertwayne/dpymenus#49]
Is there a way to set the page a menu starts on when I call .open() on it? I've browsed through the documentation and can't seem to find a way. Using a .go_to() method doesn't seem to work, as I cannot call it before opening the menu.

**Comment by robertwayne** [comment]
It will always open the first embed/page in the `add_pages()` method. Are you looking for some specific functionality other than that?

**Comment by huantianad** [comment]
I was thinking about allowing the user to specify a page to jump to when they execute the command, so if they had a specific page they wanted to look at, they could do so without scrolling through the menu.

**Comment by robertwayne** [comment]
I see! Unfortunately I don't have anything built in for that (for PaginatedMenu), but I like the idea a lot! 😄 

There's definitely a couple workarounds I can think of, but perhaps I will look into adding this in!
