### ISSUE TITLE
How to code

### ISSUE THREAD

**Issue by Jouca** [robertwayne/dpymenus#5]
Heya !
I'm interested to use your module but it's a bit confusing since the example are not very detailled with code.
The thing i want to make is embed already made with `discord.Embed` with pages and scrolling with buttons.

**Comment by robertwayne** [comment]
I added the ability to add pre-built embeds via the `add_pages` method, as well as a new piece of example code that can be found in '/examples'. See a62157482cda2a20d25a1ef8df1d702e696b10e3.

In addition, I added a lot of comments to all the example code to hopefully explain the process of creating a menu and what each piece of code does. See 4daa98c6a03473e442f7feef69180c285bed3b12.
