### ISSUE TITLE
README.md Usage examples missing commas and some formatting issues

### ISSUE THREAD

**Issue by pTinosq** [robertwayne/dpymenus#6]
It appears that a comma is missing like so:

Current:
`await menu.add_page(title='Test Page', description=f'This is just a test!', color=discord.Color.green()
                    on_next=some_func_here)`

Fixed:
`await menu.add_page(title='Test Page', description=f'This is just a test!', color=discord.Color.green(),
                    on_next=some_func_here)`

On the button menus example, there is also a strange tab at the beginning (along with the aforementioned comma issue) .

Really really great work though, you saved me a tonne of hassle!

**Comment by robertwayne** [comment]
Fixed in the cd7a4a5b6088741ae65df8ad0772f26e8ca8b6c5.
